# FOSSA configuration to override false positive license detections
# in dependencies flagged during Kubernetes 1.31 upgrade

version: 3

project:
  name: kubestellar
  team: kubestellar
  policy: kubestellar-policy

# Override incorrect license detections
overrides:
  - name: github.com/opencontainers/go-digest
    version: v1.0.0
    license: Apache-2.0
    # Scanner incorrectly flags CC-BY-SA-4.0 from docs; code is Apache-2.0

  # runc (multiple identifiers)
  - name: github.com/opencontainers/runc
    version: v1.1.13
    license: Apache-2.0
  - name: runc
    version: v1.1.13
    license: Apache-2.0

  # x/crypto (multiple identifiers)
  - name: golang.org/x/crypto
    license: BSD-3-Clause
  - name: github.com/golang/crypto
    license: BSD-3-Clause
  - name: crypto
    license: BSD-3-Clause

  # kubernetes repo identifier variants
  - name: k8s.io/kubernetes
    version: v1.31.13
    license: Apache-2.0
  - name: github.com/kubernetes/kubernetes
    version: v1.31.13
    license: Apache-2.0
  - name: kubernetes
    license: Apache-2.0
    # FOSSA sometimes flags openssl-ssleay from docs/third_party; code is Apache-2.0

# Exclude documentation-only files that trigger license false positives
exclude:
  - "**/*.md"
  - "**/LICENSE.docs"
  - "**/CONTRIBUTING*"
  - "**/docs/**"
  - "**/examples/**"